name: '🗃️ Wiki migration'
labels: 'documentation'
description: 'Migrating Jenkins Wiki pages to jenkins.io'

body:
  - type: input
    attributes:
      label: Page to migrate
    validations:
      required: true
  - type: input
    attributes:
      label: Destination on jenkins.io
    validations:
      required: true
  - type: textarea
    attributes:
      label: Migration notes
      placeholder: If there are any considerations to keep in mind during the migration, please add them here
  - type: markdown
    attributes:
      value: | 
        "For contributors: [Wiki Migration Guidelines](https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#moving-documentation-from-jenkins-wiki)"
