name: '🐛 Bug report'
labels: 'bug'
description: 'Create a bug report to the website'

body:
  - type: input
    id: problem
    attributes:
      label: Problem with this page
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible solution
      description: If you have suggestions on a fix for the bug, please describe it here.
